services:
  ocr-api:
    build: .
    container_name: peri_ocr
    ports:
      - "8000:8000"
    restart: always
    # volumes:
    #   - .:/app
    environment:
      - DISABLE_MODEL_SOURCE_CHECK=True
      - DEBUG=False